### ISSUE TITLE
blaze.css does not work standalone in shadow DOM

### ISSUE THREAD

**Issue by quotquot** [BlazeSoftware/css#1]
I have been using blaze.css since version 1.0. Great stuff, thank you. But for at least the past year I have had rendering problems with inputs and toggles. I tried many times to understand what the problem was and never managed to. Recently I tried once more to use blaze in a web component and ran into the same issues as in the past. I tried to create a minimal test to reproduce the rendering problems and found the following way:

For the test, download a copy of the latest `blaze.css`:
```shell
$ wget https://unpkg.com/@blaze/css@x.x.x/dist/blaze/blaze.css
```
Create the following `index.html`, 70% of which is simply the login-example code from `blazeui.com`:
```html
<!doctype html>
<html>
  <body>
    <template>
      <link rel="stylesheet" href="blaze.css">
      <!-- START CONTENT FROM https://www.blazeui.com/examples/login -->
      <form class="o-container o-container--xsmall c-card u-high">
        <header class="c-card__header">
          <h2 class="c-heading">
            Login
            <div class="c-heading__sub">Existing users</div>
          </h2>
        </header>
        <div class="c-card__body">
          <div class="o-form-element">
            <label class="c-label">
              Email:
              <input class="c-field c-field--label" type="email" placeholder="your@email.com" />
              <div role="tooltip" class="c-hint">
                The email used to register the account
              </div>
            </label>
          </div>
          <label class="o-form-element c-label">
            Password:
            <input class="c-field c-field--label" type="password" />
          </label>
          <div class="o-form-element">
            <label class="c-toggle c-toggle--success">
              Remember me?
              <input type="checkbox" checked />
              <div class="c-toggle__track">
                <div class="c-toggle__handle"></div>
              </div>
            </label>
          </div>
        </div>
        <footer class="c-card__footer">
          <button type="button" class="c-button c-button--brand c-button--block">
            Login
          </button>
        </footer>
      </form>
      <!-- END CONTENT FROM https://www.blazeui.com/examples/login -->
    </template>
    <script>
        class LoginFormElement extends HTMLElement {
            connectedCallback() {
                const template = document.querySelector('template');
                const shadowRoot = this.attachShadow({mode:'open'});
                shadowRoot.appendChild(template.content.cloneNode(true));
            }
        }
        window.customElements.define('login-form', LoginFormElement);
        document.body.appendChild(document.createElement('login-form'));
    </script>
  </body>
</html>
```
Rendering `index.html` in a browser (I tried both Chromium 81 and Firefox 68 ESR) yields:

![blaze1](https://user-images.githubusercontent.com/32509844/79066997-5df11d00-7cbc-11ea-9090-8f6ece57c982.png)

The reason for that faulty rendering is that blaze defines its CSS variables on `:root` and those variables do not cross into the component. The first idea is to define the variables on both `:root` and `:host`:
```shell
$ sed -i s/:root/:root,:host/ blaze.css
```
This time, the login page renders a little better but has the two issues I have had for one or two years: the inputs stretch to the border of the container, and the toggle has an extra piece on its track:

![blaze2](https://user-images.githubusercontent.com/32509844/79067010-8c6ef800-7cbc-11ea-9698-75e13845f235.png)

But it's more complicated than that: in my project interface, I don't have the stretched button, and it's rather easy to get the correct rendering inside the component by some random tricks, for example by duplicating the `link` element in the light DOM (I have no idea why that makes a difference, it means some CSS information crosses the component barrier). But I have never been able to get the correct rendering in my components.

I hope it helps (and that any answer to this issue will hopefully help me solve my longstanding issue).

**Comment by gregorypratt** [comment]
Hmmm, I've managed to re-create this, it's rather odd but I'll try and find a fix

**Comment by gregorypratt** [comment]
Hmmm, I've managed to re-create this, it's rather odd but I'll try and find a fix

**Comment by gregorypratt** [comment]
https://codepen.io/gregorypratt/pen/BaoQmRv?editors=1000

Think I've fixed it as part of 9.2.0...if it isn't please feel free to re-open the issue 👍 

And next time don't wait so long! Here to help! 😄

**Comment by quotquot** [comment]
Thank you, it's working now. Initially it still did not work in my component but I realized today that the order of the css “parts” does matter; I thought it did not. I switched to the “official” import order and it is working now.

I did not report the problem earlier because I could not reproduce it outside of my project, and I am using blaze in an unsual way. In fact, I am using blaze like it used to be in its early versions, with separate .css files, which I generate from the source:

```
components.addresses.css       components.lists.css       objects.grid.css
components.alerts.css          components.navs.css        objects.grid.responsive.css
components.avatars.css         components.overlays.css    objects.images.css
components.back-to-top.css     components.pagination.css  objects.media.css
components.badges.css          components.progress.css    objects.modals.css
components.breadcrumbs.css     components.ranges.css      objects.panels.css
components.buttons.css         components.tables.css      utilities.alignment.css
components.calendars.css       components.tabs.css        utilities.boxing.css
components.cards.css           components.tags.css        utilities.elevation.css
components.divider.css         components.timelines.css   utilities.radius.css
components.file-upload.css     components.toggles.css     utilities.sizes.css
components.github-buttons.css  components.tooltips.css    utilities.typography.css
components.headings.css        components.trees.css       utilities.visibility.css
components.hints.css           generics.global.css        variables.host.css
components.input-groups.css    objects.containers.css     variables.root.css
components.inputs.css          objects.drawers.css
components.links.css           objects.forms.css
```

Note that I have two `variables` files, I inject one or the other depending on where I use it, in light DOM or shadow DOM. (One problem with the change you made in 9.2.0 is that a component actually changes the state of `:root`, which is a little strange. With two files, the component only changes the state of its own `:host`.) Then I inject (using [`adoptedStyleSheets`] when available, so it's efficient) the other stylesheets which my component needs, and nothing more. And I thought the separate styles were independent enough that I could add them in any order, but apparently a wrong order gave me these stretched input fields. Now I am enforcing the insertion order and it works.

While I am here, maybe I can ask that quick question: `blazeui.com` uses the `o-page-header` class, which I could not find in the distribution, it's quite useful, could it be added in the official stylesheet somehow? I seem to remember it was part of the early versions, but I may be wrong.

Thanks again.

[`adoptedStyleSheets`]: https://developers.google.com/web/updates/2019/02/constructable-stylesheets

**Comment by gregorypratt** [comment]
All `o-page-header` does is this:

```css
.o-page-header {
  position: relative;
  border-bottom: 1px solid #eee;
}
```

Didn't seem worthy of being included in the Toolkit!

If you'd like a new component then by all means either open a new issue or PR and I'll take a look. But if it's just the above then it's not really useful enough...

**Comment by quotquot** [comment]
Technically, from what I gathered, it has two more properties:
```css
.o-page-header {
    margin: auto;
    max-width: 64em;
    position: relative;
    border-bottom: 1px solid #eee;
}
```
Still I agree it's rather simple. I guess it's the naming o-* wich led me to search for this class in blaze.css. I am not good enough in CSS to submit a PR but I will open an issue for an “app header”.
