### ISSUE TITLE
Provide an app-header component

### ISSUE THREAD

**Issue by quotquot** [BlazeSoftware/css#2]
As a followup to https://github.com/BlazeSoftware/css/issues/1, my impression is that blaze.css could gain at implementing an “app header”, by extending the `o-page-header` class used by the `blazeui.com` site into something close to Polymer's [`app-header`](https://github.com/PolymerElements/app-layout/tree/master/app-header) component, visible for example in the [chromium-dash application](https://chromiumdash.appspot.com).

**Comment by gregorypratt** [comment]
Another nice idea, would you like to create a PR and I'll review it?
