### ISSUE TITLE
Allow the use of c-icon with c-button

### ISSUE THREAD

**Issue by quotquot** [BlazeSoftware/css#4]
I would like to create a button with an icon like it is possible to do with inputs, for example with a lock icon to show that a form submission is secure. As far as I can tell, it could be easy to allow the c-icon rules to apply to buttons too, though I guess it would require to rename the `o-field` classes and there needs to be some changes for buttons that are not `c-button--block`. An html document that illustrates the idea and some positioning issues:
```html
<!doctype html>
<html>
  <body>
    <link rel="stylesheet" href="https://unpkg.com/@blaze/css@x.x.x/dist/blaze/blaze.css">
    <script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <style>
     .o-field--icon-left .c-button {
         padding-left: calc(var(--spacing-small)*4);
     }
     .o-field--icon-right .c-button {
         padding-right: calc(var(--spacing-small)*4);
     }
     .o-field--icon-right .c-button+.c-icon {
         right: var(--spacing-small);
     }
    </style>
    <div class="o-container o-container--xsmall">
      <div class="o-field o-field--icon-left o-field--icon-right">
        <i class="fas fa-lock c-icon"></i>
        <a class="c-button c-button--block">Submit</a>
        <i class="fas fa-lock c-icon" aria-hidden></i>
      </div>
      <div class="u-center-block">
        <div class="u-center-block__content u-center-block__content--horizontal">
          <div class="o-field o-field--icon-left o-field--icon-right">
            <i class="fas fa-lock c-icon"></i>
            <a class="c-button">Submit</a>
            <i class="fas fa-lock c-icon" aria-hidden></i>
          </div>
        </div>
      </div>
      <div class="o-field o-field--icon-left o-field--icon-right u-window-box-super">
        <i class="fas fa-lock c-icon"></i>
        <a class="c-button">Submit</a>
        <i class="fas fa-lock c-icon" aria-hidden></i>
      </div>
    </div>
  </body>
</html>
```
which renders as:
![button-icon](https://user-images.githubusercontent.com/32509844/82316376-f9b52d80-99cc-11ea-9fd1-f917df23d04d.png)
The example is pretty ugly but, with only one icon in a real page, with the right colors, it's alright.

**Comment by gregorypratt** [comment]
Hmmm, I think for almost all cases you would want the icon adjacent to the text of the button to reduce cognitive load of the user to associate the icon to the action of the button.

Which you can do by plonking an icon inside the button as is... 

```html
<button type="button" class="c-button c-button--brand u-super">Button <i class="fas fa-lock c-icon"></i></button>
```

<img width="189" alt="Screenshot 2020-06-25 at 14 20 42" src="https://user-images.githubusercontent.com/1453899/85727634-1987f180-b6ef-11ea-9517-075eeb1c9a43.png">
<img width="1011" alt="Screenshot 2020-06-25 at 14 20 22" src="https://user-images.githubusercontent.com/1453899/85727639-1a208800-b6ef-11ea-9f21-16f5aafcc2b7.png">
<img width="194" alt="Screenshot 2020-06-25 at 14 20 03" src="https://user-images.githubusercontent.com/1453899/85727641-1ab91e80-b6ef-11ea-80b7-30f039e0880a.png">
